### ISSUE TITLE
Allow For Variable Jump Height

### ISSUE THREAD

**Issue by annahlee** [ucsb-cs56-projects/cs56-games-country-runner#81]
Current jump height makes it difficult to dodge oncoming monsters because of the amount of time the player spends in the air. We plan to make it shorter (but still obey the laws of physics).

**Comment by joelbagan** [comment]
Instead of simply changing the height of the jump, allow for variable jump height. Think of 2D Mario games, where your jump height is determined by how long you hold the jump button. You can achieve a maximum height jump by holding the jump button for the duration of the jump (or at least the upward half of the jump), and similarly a minimum height jump by tapping the jump button very quickly.

F17 OK (150-200pts)

**Comment by Sierrasch** [comment]
W18 OK (200 pts)

**Comment by Sierrasch** [comment]
Done W18
